<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AutoFan.Storage</RootNamespace>
    <AssemblyName>AutoFan.Storage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoFan.Core\AutoFan.Core.csproj" />
  </ItemGroup>

</Project>
