<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>AutoFan.App</RootNamespace>
    <AssemblyName>AutoFan.App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoFan.Core\AutoFan.Core.csproj" />
    <ProjectReference Include="..\AutoFan.Hardware\AutoFan.Hardware.csproj" />
    <ProjectReference Include="..\AutoFan.Storage\AutoFan.Storage.csproj" />
  </ItemGroup>

</Project>
